---
# tasks file for git

- name: Install Git
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ git_packages }}"
  when: (install_from_source == false) and (ansible_os_family == 'RedHat')

- import_tasks: install-from-source.yml
  when: install_from_source == true
